#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping $app's systemd services..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE CONFIGURATION
#=================================================
ynh_script_progression "Updating $app's configuration..."

ynh_config_add --template="norish.env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
