#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

# Remove main app service
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

# Remove Chromium service
if ynh_hide_warnings yunohost service status "${app}-chromium" >/dev/null; then
    yunohost service remove "${app}-chromium"
fi
ynh_config_remove_systemd --service="${app}-chromium"

ynh_config_remove_nginx

# Remove log directory
ynh_safe_rm "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
